### ISSUE TITLE
Locate me has low accuracy

### ISSUE THREAD

**Issue by baffioso** [mapcentia/gc2collector#13]
Seems like "Locate me" is not as precise as other apps using the GPS on an iPad. Have experienced that the cross on the map is placed serveral hundred meters from my actual location. Is it possible to improve accuracy?

**Comment by mapcentia** [comment]
I'm not sure. It uses the HTML5 location API, which means that the position is passed from the OS. Does the device locate better on the native Apple Map app?

**Comment by baffioso** [comment]
Just tested on two android phones, where I'm having no problem with GPS accuracy. Seems like this issue is related to apple\ipad. Native Apple map app has good accuracy.

**Comment by ArtificialTruth** [comment]
I can confirm this too.
I guess the HTML5 API gets updates/makes calls from/to the OS less frequently, so that the position never gets exact enough.

**Comment by mapcentia** [comment]
There is some attributes, you can pass to the Geolocation API. "enableHighAccuracy" is now true. There is also "timeOut", which is set to 7000ms. It may be that there are differences in how the API is implemented by the various manufacturers. 

https://dev.w3.org/geo/api/spec-source.html#high-accuracy

**Comment by baffioso** [comment]
We have just tested on iphone 5s today and are still experiencing very low accuracy ( ~ 200 m).  Is there any way this could be improved?
