### ISSUE TITLE
Setup base layers

### ISSUE THREAD

**Issue by baffioso** [mapcentia/gc2collector#6]
Would be nice to add more base layers to the app

**Comment by mapcentia** [comment]
Its possible to set available baselayers by this config in App.php

// Available baselayers in Collector
        "baseLayersCollector" => [
            ["id" => "osm", "name" => "OSM"],
            ["id" => "stamenToner", "name" => "Stamen Toner"],
            ["id" => "mapQuestOSM", "name" => "MapQuset OSM"],
        ],

GC2 layers can be added like this:
 ["id" => "my_schema.my_layer", "db"=>"my_database", "name" => "My layer"],
