### ISSUE TITLE
Hard to get feature info window from point 

### ISSUE THREAD

**Issue by baffioso** [mapcentia/gc2collector#7]
Its hard to hit the point and get feature info.

**Comment by mapcentia** [comment]
The select buffer must be bigger

**Comment by mapcentia** [comment]
Its now 10 \* map-resolution in pixels. Before it was 5 *. Check if this OK?

**Comment by baffioso** [comment]
This is much better, thanks

**Comment by baffioso** [comment]
Can you increase the select buffer a bit. Still having problems getting feature info.

**Comment by mapcentia** [comment]
Its now 10 \* map-resolution in pixels.

**Comment by mapcentia** [comment]
Last comment was wrong. Its now 15 \* map-resolution in pixels.
